# Generated by Django 5.0.6 on 2024-08-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentMF',
            new_name='Student',
        ),
    ]
